- mangum/adapter.py
- mangum/protocols/__init__.py
Raises an exception currently when importing the handlers. Probably a better way to do this, but this will fix the import error when websockets aren't being used.
> Only websockets require boto3, handle import separately

- README.md
- docs/index.md
- mangum/adapter.py
- mangum/protocols/http.py
- tests/test_http.py
Refs https://github.com/erm/mangum/issues/60
* Wrapping the ASGI cycle run method to allow application frameworks (such as FastAPI and Starlette) to handle exception behaviour.
* Removing the `debug` statement (for now) - will probably re-introduce some generic form later.
> Allow applications to handle exceptions, remove debug option, tests/docs

- mangum/adapter.py
- mangum/connections.py
- mangum/lifespan.py
- mangum/protocols/http.py
- mangum/protocols/websockets.py
- mangum/types.py
- scripts/test
- setup.cfg
Resolves #67.
I had to swap `@dataclass`es for `__init__(self, *args)` syntax to placate mypy.  It isn't ideal, but it was less dumb than other possible workarounds, such as having self.app be a tuple of (app: ASGIApp,).
<details><summary>demonstration of the trouble with <code>@dataclass</code></summary>
```python
from dataclasses import dataclass
from typing import Callable, Dict
Foo = Callable[[Dict[str, str]], int]
def foo(d: Dict[str, str]) -> int:
return len(list(d.keys()))
@dataclass
class Bar:
foo: Foo  # mypy thinks the first argument is `self`!
def run(self, d: Dict[str, str]) -> None:
print(self.foo(d))
bar = Bar(foo)
bar.run({"a": "1"})  # works, but doesn't pass the type checker
class Baz(object):
def __init__(self, foo: Foo):
self.foo = foo  # explicit enough that mypy …
```
> fixed type checking errors.

- tests/conftest.py
- tests/test_http.py
- tests/test_lifespan.py
This PR adds unittest for `query_string`
@erm 
I add a test for request and change `mock_http_event` to support query parameters.
If you don't prefer the change then, please tell me it. 
https://github.com/erm/mangum/issues/80
> add unitest for query_string

- mangum/adapter.py
- tests/test_http.py
PR to handle non-root base path of API Gateway custom domain.
Details can be found in https://github.com/erm/mangum/issues/78
> add strip_base_path

- mangum/adapter.py
as in some case (especially right after a new release ?) api gateway does not seem to send the header key in the event
> make 'headers' key in event optional

- mangum/adapter.py
This fixes a bug that prevents testing via API Gateway console.
**Steps to reproduce:**
1. Deploy ASGI app on AWS Lambda using mangum handler, configured to run behind API Gateway with `{proxy+}` path and `ANY` method.
3. In the API Gateway console, go to the method and select "TEST".
4. Set the method to `GET` and path to any valid path to GET from your app, but leave the Headers textarea empty.
**Problem**
Mangum throws the following exception:
```
File "/var/task/mangum/adapter.py", line 60, in __call__
raise exc
File "/var/task/mangum/adapter.py", line 58, in __call__
response = self.handler(event, context)
File "/var/task/mangum/adapter.py", line 72, in handler
response = self.handle_http(event, context)
File "/var/task/mangum/adapter.py", line 84, in handle_http
server, client = …
```
> Support testing with no headers

- mangum/types.py
mangum was checking for more concrete types than fastapi, causing errors when one was running mypy
it should fixes https://github.com/erm/mangum-examples/issues/2
> fix types between mangum and fastapi

- mangum/adapter.py
- tests/conftest.py
- tests/test_http.py
The proposed changes in this pull request brings initial support for the new HTTP API .
The _event_ dictionary passed to lambda from the new  [HTTP API](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html) is different from the one expected from the traditional REST API therefore mangum fails in looking up some of the expected keys.
> adding support for api gateway's new http apis

- mangum/backends/dynamodb.py
- tests/test_backends.py
This PR improves Dynamodb table name for backend.
I have copied code from python source code to create a function that gets table function.
https://github.com/python/cpython/blob/9d17cbf33df7cfb67ca0f37f6463ba5c18676641/Lib/urllib/parse.py#L198-L210
The function doesn't treat IPv6 style domain name.
I think don't need to care for Dynamodb.
https://github.com/python/cpython/blob/9d17cbf33df7cfb67ca0f37f6463ba5c18676641/Lib/urllib/parse.py#L156-L165
I have added test cases following naming rule patterns.
*Table names and index names must be between 3 and 255 characters long, and can contain only the following characters:*
- `a-z`
- `A-Z`
- `0-9`
- `_` (underscore)
- `-` (dash)
- `.` (dot)
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html …
> Improve Dynamodb table name

- mangum/adapter.py
- tests/test_websockets.py
This PR supports WebSockets without a body.
@erm 
I thought I should use `pytest.parametrize`  for this unittest.
But, I think It's too complex in the case.
Therefore, I deleted the `body` in an event dict.
#117
> support WebSockets without body

- mangum/adapter.py
- mangum/config.py
- mangum/protocols/http.py
- mangum/websocket.py
- tests/test_backends.py
- tests/test_http.py
This adds a `Config` class to store the configuration for the adapter instance to manage the configurable fields and to build the scope. This doesn't change the behaviour, but will make it easier for me to develop the WebSocket implementation by separating the configuration from the main adapter class handler methods.
> Configuration class, scope methods

- mangum/protocols/http.py
- tests/test_http.py
@jordaneremieff 
I suggest to support  `multiValueHeaders` on Response.
I want to set the same-name cookies.
`FastAPI` + `uvicorn` can return same-name cookies.
But, Mangum returned only the last cookie. the first cookie is dropped.
Mangum should support `multiValueHeaders` to resolve the problem. 
This change affects a little bit of performance.
If You prefer this PR, then I will add test the code.
How do you think about it?
https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format
example
```python
from fastapi import FastAPI
from starlette.responses import Response
from mangum import Mangum
app = FastAPI()
@app.get('/')
def get_root():
response = Response()
response.set_cookie('test', 'value1') …
```
> Support multiValueHeaders on Response

- tests/test_http.py
Hi there, this project is super cool! ❤️ 
While I was looking through the code, I noticed that there was a re-declaration of a test (`test_http_request` was declared twice in `test_http.py` \[[1](https://github.com/jordaneremieff/mangum/blob/f20dbda41567ba5e161a0f6db74c68311ae80c0a/tests/test_http.py#L26) [2](https://github.com/jordaneremieff/mangum/blob/f20dbda41567ba5e161a0f6db74c68311ae80c0a/tests/test_http.py#L548)\]) which was preventing one of the tests from running.
This PR renames the duplicate test and fixes the resulting test failure that was exposed!
Also, I noticed the `test_http_response_headers` test appears to be duplicated so I removed the duplicate.
> Fix duplicate test names preventing test runs.

- .gitignore
- mangum/adapter.py
- requirements.txt
Only appends a prefix to the `api_gw_base_path` if it's not there already to avoid duplicate prefix slashes.
Issue: https://github.com/jordaneremieff/mangum/issues/137
Intended Design Change
```python3
api_gw_base_path = "prod"
api_gw_base_path = "/prod"
def lambda_handler(event, context):  # pragma: no cover
handler = mangum.Mangum(api, api_gateway_base_path=settings.api_gw_base_path.lstrip("/"))  #137 Avoids the need for all consumers to call .lstrip("/") on their base path str
response = handler(event, context)
return response
```
> Only prefix a slash on the api_gateway_base_path if needed

- mangum/protocols/http.py
- requirements.txt
- tests/test_http.py
This PR fixes #139. 
It adds a new test based on the gzip test, where the only change is the compress algorithm library from `gzip` to `brotli`.
> Add support to brotli compress

- mangum/adapter.py
It looks like this was accidentally removed in 91f5bebc6429dcbbb3328d2aae72dfa02fd0f87b
> Re-instate api_gateway_base_path comment

- mangum/adapter.py
- requirements.txt
- Add type hints for lambda handler context parameter
> AWS Lambda context type hinting

- mangum/adapter.py
* Simplify magnum call function
* extract event processing into dedicated functions
This is a required abstraction to create non-AWS event handlers.
> Extract ASGI scope creation into function

- mangum/adapter.py
- mangum/handlers/abstract_handler.py
- mangum/handlers/aws_alb.py
- mangum/handlers/aws_api_gateway.py
- mangum/handlers/aws_cf_lambda_at_edge.py
- mangum/handlers/aws_http_gateway.py
- mangum/protocols/http.py
- mangum/types.py
- tests/handlers/test_aws_alb.py
- tests/handlers/test_aws_api_gateway.py
- tests/handlers/test_aws_cf_lambda_at_edge.py
- tests/handlers/test_aws_http_gateway.py
Renamed `scope` to `request` in the handler classes, accessing scope as a single type on the request, adjusted docstrings, removed typing import, some minor formatting changes - no changes to behavior.
Docs probably need updates but this can be done prior to next release.
> Renaming and formatting

- mangum/handlers/aws_alb.py
- mangum/handlers/aws_api_gateway.py
- mangum/handlers/aws_cf_lambda_at_edge.py
- mangum/handlers/aws_http_gateway.py
- tests/handlers/test_aws_alb.py
- tests/handlers/test_aws_api_gateway.py
- tests/handlers/test_aws_cf_lambda_at_edge.py
- tests/handlers/test_aws_http_gateway.py
I believe this closes #181. 
All tests pass, and I have tested the solution on a live lambda function being severed by ALB. 
The type annotations suggest that `def body(self) -> bytes:` should ALWAYS return bytes. However the code (and tests) sometimes returns None. In these cases I forced the None to return an empty byte string: `b""`.  As a result most of the methods now look like this:
```python
@property
def body(self) -> bytes:
body = self.trigger_event.get("body", b"")
if not body:
body = b""
if self.trigger_event.get("isBase64Encoded", False):
return base64.b64decode(body)
if not isinstance(body, bytes):
body = body.encode()
return body
```
If that is incorrect I can update my PR to reflect that `bytes` OR `None` can be returned from `def body(self)` and remove the code that forces …
> #181 - ensure bytes are always returned from .body() method

- mangum/handlers/aws_alb.py
- tests/handlers/test_aws_alb.py
I believe this fixes #185 by adding back the code used in 0.11.0.
```python
def handle_headers(
self,
response_headers: List[List[bytes]],
) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
headers, multi_value_headers = self._handle_multi_value_headers(
response_headers
)
if "multiValueHeaders" not in self.trigger_event:
for key, values in multi_value_headers.items():
if len(values) > 1:
for value, cased_key in zip(values, all_casings(key)):
headers[cased_key] = value
multi_value_headers = {}
return headers, multi_value_headers
```
Let me know if anything else should be added or removed.
> #185 ALB/ELB set cookies when multiValueHeaders is not set

- mangum/handlers/aws_alb.py
- tests/handlers/test_aws_alb.py
I believe this closes issue #178. See the issue for a discussion of the bug. Tests pass, and I have tested this on a lambda function being served by an ALB.
In short: "If the query parameters are URL-encoded, the load balancer does not decode them. You must decode them in your Lambda function."
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html
Thanks to @jurasofish for initially finding the issue and writing the failing test. This PR includes his commit from #179, which can be closed if this PR is merged.
I don't know if something similar needs to be applied to the other handlers, not as familiar / not using those trigger methods.
_Minor mishap with GitHub which is why  https://github.com/jordaneremieff/mangum/pull/183 got closed... my bad._
> #178 alb url double encoding

- mangum/handlers/aws_alb.py
- tests/handlers/test_aws_alb.py
Fix broken multi value headers for ALB, as described in #187.
This is largely a copy past of #179 just with some small changes.
Sorry the changes to testing are so substantial, just had to add a lot of logic to handle with/without multi value headers.
Closes #187
Closes #179 
I spoke to AWS support about the case mutations.
They wouldn't guarantee it as a supported way of using ALB, but they didn't say it wasn't supported either....
They guy just spun up an ALB and confirmed empirically that it worked, which we already knew.
Whatever, it didn't hurt to ask
> Fix ALB multi value headers

- mangum/handlers/aws_api_gateway.py
- tests/handlers/test_aws_api_gateway.py
All of the previous releases use `api_gateway_base_path`, reverting the name change.
> Revert "base_path" -> "api_gateway_base_path"

- mangum/backends/__init__.py
Refs https://github.com/jordaneremieff/mangum/issues/196
Boto3 should be optional dependency required only for WebSocket support.
> Make boto3 optional

- mangum/handlers/abstract_handler.py
- mangum/handlers/aws_api_gateway.py
- mangum/handlers/aws_http_gateway.py
> Fix unhandled api_gateway_base_path in AwsHttpGateway

- mangum/handlers/aws_http_gateway.py
- tests/conftest.py
- tests/handlers/test_aws_http_gateway.py
- tests/test_http.py
HTTP Gateway V2 drops both the multiValueHeaders and
multiValueQueryStringParameters elements.
With this change:
* Cookies passed to request and response as cookie element
containing list of all cookie values.
* Headers with multiple values are concatenated through comma
and passed under Headers element instead of the obsolete
multiValueHeaders.
https://medium.com/@lancers/amazon-api-gateway-explaining-lambda-payload-version-2-0-in-http-api-24b0b4db5d36
https://aws.amazon.com/blogs/compute/building-better-apis-http-apis-now-generally-available/
Addresses issue #215.
> HTTP Gateway V2: Remove use of obsolete multiValueHeaders

- .github/workflows/test.yml
- requirements.txt
- setup.py
- tests/test_lifespan.py
- Added python3.9 and 3.10 tests to CI
- Added python3.9 and 3.10 classifiers to `setup.py`
- Changed `Quart` python version constraint, Quart now supports python 3.7 and above
- Adjusted tests to reflect the Quart version change
> Added explicit python3.9 and 3.10 support

- mangum/handlers/aws_api_gateway.py
- tests/handlers/test_aws_api_gateway.py
When calling a Lambda via a AWS API Gateway, you are supposed to be able to use both normal headers and "multiValueHeaders" as described here: ["Multi-value headers as well as single-value headers and parameters can be combined in the same requests and responses."](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#apigateway-multivalue-headers-and-parameters)
I fixed this by simply checking for both keys in the event dict and updating the resulting headers dict first with the normal headers and then with the multiValueHeaders, so they still take precedence.
> Fix aws_api_gateway handler not accepting combined headers and multiValueHeaders

- README.md
- docs/lifespan.md
The Websocket support was removed in latest version but it's still mentioned in README and the docs. Should it be removed?
This is just a sample, there are other references to Websocket support.
> Removing Websocket from docs

- CONTRIBUTING.md
- docs/contributing.md
- setup.py
- tests/test_lifespan.py
Refs https://github.com/jordaneremieff/mangum/issues/245
> :pushpin: Remove references to Python 3.6, update setup.py.

- .gitignore
- mangum/adapter.py
- mangum/handlers/alb.py
- mangum/handlers/api_gateway.py
- mangum/handlers/lambda_at_edge.py
- mangum/protocols/http.py
- mangum/protocols/lifespan.py
- mangum/types.py
- tests/handlers/test_custom.py
Refers to https://github.com/jordaneremieff/mangum/issues/247 and https://github.com/jordaneremieff/mangum/discussions/257
> :recycle: Relax type annotations, refactor custom handler inferences, naming

- README.md
- docs/index.md
I've been using `mangum` with `django` for several months now, and I have to say it works pretty well.
The docs already include hints on how to set it up, but it's not very obvious that it's well supported at first sight.
> Mention that Django works fine too

- .gitignore
- docs/adapter.md
- mangum/adapter.py
- mangum/handlers/alb.py
- mangum/handlers/api_gateway.py
- mangum/handlers/lambda_at_edge.py
- mangum/handlers/utils.py
- mangum/types.py
- tests/handlers/test_alb.py
- tests/handlers/test_api_gateway.py
- tests/handlers/test_http_gateway.py
- tests/handlers/test_lambda_at_edge.py
- tests/test_adapter.py
Added optional `text_mime_types` argument to:
- `Mangum` adapter's `__init__` method
- `handle_base64_response_body` function (this function is the target recipient of the `text_mime_types` list)
This argument is optional and by default references the same `DEFAULT_TEXT_MIME_TYPES` list.
**WARNING**: old solutions involving editing the `DEFAULT_TEXT_MIME_TYPES` list are now broken because this list was moved from `mangum/handlers/utils.py` to `mangum/adapter.py`.
resolves #275
> Added text_mime_types argument

- docs/asgi-frameworks.md
Both FastAPI and Sanic have dropped support for Python 3.6.
We could also update the docs to say +3.7 but I thought it would be easier to just get rid of it?
> Remove 3.6 reference from frameworks docs

- docs/external-links.md
Adding blog post https://aminalaee.dev/posts/2022/fastapi-aws-lambda/ to the external links docs.
> Add new blog post to external links

- docs/asgi-frameworks.md
The docs/asgi.md has been renamed to docs/asgi-frameworks.md in https://github.com/jordaneremieff/mangum/pull/111
> Fix a broken link to asgi-frameworks limitations

- README.md
This domain expired and is now being used to host an ai spam blog
> doc: remove expired domain from README

- CONTRIBUTING.md
Adding link to uv installation page, which is needed in order to run the setup script.
> Add uv installation requirement
